push:
    branches:
        - master
pull-request:
    branches:
        - master

jobs:
    build:
        name: Azure pipeline
        runs-on: Default
        steps:
        - name: Azure Pipeline Actions
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: 
            azure-pipeline-name: 'Sudheerkunda.github-workflow'
            azure-devops-token: ${{ secrets.AZURE_DEVPS_TOKEN }}

            testing line